---

- name: Apache installation playbook
  hosts: all
  become: true

  tasks:
    - name: Update repository index
      apt:
        update_cache: true

    - name: Installing apache2 package
      apt:
        name: apache2 
        state: latest

    - name: Ensure the apache server has started 
      service:
        name: apache2
        state: started
