---

- name: Site playbook
  hosts: all
  become: true
  tasks:
    - name: Install updates (CentOS)
      tags: always
      dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution == "CentOS"

    - name: Install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
    - name: Install apache and php (Ubunut) 
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php 
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install apache and php (CentOS)
      tags: apache,httpd,centos
      dnf:
        name:
         - httpd
         - php
        state: latest
      when: ansible_distribution == "CentOS" 

    - name: Copy the default index to site
      tags: apache,apache2,httpd
      copy:
        src: default_index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644      
 

- hosts: db_servers
  become: true
  tasks:
    - name: Install mariadb (CentOS)
      tags: db,mariadb,centos
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS" 

    - name: Install mariadb (Ubuntu)
      tags: db,mariadb,ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu" 
 
- hosts: file_servers
  become: true
  tasks:
    - name: Install samba package
      tags: samba,file
      package:
          name: samba
          state: latest 
