- name: Install apache and php 
  tags: apache,apache2,httpd
  package:
    name:
     - "{{ apache_package_name }}"
     - "{{ php_package_name }}"
    state: latest


- name: Start and enable apache service 
  tags: apache,httpd,apache2
  service:
     name: "{{ apache_service }}" 
     state: started
     enabled: true

- name: Change admin server email in httpd config file
  tags: apache,centos,httpd
  lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin somebody@somedomain.com
  when: ansible_distribution == "CentOS"
  register: apache

- name: Restart apache service
  tags: apache,centos,httpd
  service:
        name: "{{ apache_service }}"
        state: restarted
  when: apache.changed

- name: Copy the default index to site
  tags: apache,apache2,httpd
  copy:
     src: default_index.html
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644
